=== michaelschwarz1/swe/shop/src/test/resources/datasets/db.dtd
<!ELEMENT dataset (
    KUNDE*,
    ADRESSE*,
    ARTIKEL*,
    BESTELLUNG*,
    POSITION*)>

<!ELEMENT KUNDE EMPTY>
<!ATTLIST KUNDE
    PK_KUNDE CDATA #REQUIRED
    NACHNAME CDATA #REQUIRED
    VORNAME CDATA #IMPLIED
    EMAIL CDATA #REQUIRED
    PASSWORD CDATA #IMPLIED
    ERZEUGT CDATA #REQUIRED
    AKTUALISIERT CDATA #REQUIRED
>

<!ELEMENT ADRESSE EMPTY>
<!ATTLIST ADRESSE
    PK_ADRESSE CDATA #REQUIRED
    PLZ CDATA #REQUIRED
    ORT CDATA #REQUIRED
    STRASSE CDATA #IMPLIED
    HAUSNR CDATA #IMPLIED
    FK_KUNDE CDATA #REQUIRED
    ERZEUGT CDATA #REQUIRED
    AKTUALISIERT CDATA #REQUIRED
>

<!ELEMENT ARTIKEL EMPTY>
<!ATTLIST ARTIKEL
    PK_ARTIKEL CDATA #REQUIRED
    KATEGORIE CDATA #REQUIRED
    BESCHREIBUNG CDATA #REQUIRED
    PREIS CDATA #IMPLIED
    AUF_LAGER CDATA #REQUIRED
    ERZEUGT CDATA #REQUIRED
    AKTUALISIERT CDATA #REQUIRED
>

<!ELEMENT BESTELLUNG EMPTY>
<!ATTLIST BESTELLUNG
    PK_BESTELLUNG CDATA #REQUIRED
    FK_KUNDE CDATA #REQUIRED
    IDX CDATA #REQUIRED
    ERZEUGT CDATA #REQUIRED
    AKTUALISIERT CDATA #REQUIRED
>

<!ELEMENT POSITION EMPTY>
<!ATTLIST POSITION
    PK_POSITION CDATA #REQUIRED
    FK_BESTELLUNG CDATA #REQUIRED
    FK_ARTIKEL CDATA #REQUIRED
    ANZAHL CDATA #REQUIRED
    IDX CDATA #REQUIRED
    ERZEUGT CDATA #REQUIRED
    AKTUALISIERT CDATA #REQUIRED
>

=== michaelschwarz1/swe/shop/src/test/resources/datasets/db.xml
<?xml version='1.0' encoding='ISO-8859-1'?>
<!DOCTYPE dataset SYSTEM "db.dtd">
<dataset>
  <KUNDE PK_KUNDE="201" NACHNAME="Schwarz" VORNAME="Michael" EMAIL="scmi1025@hs-karlsruhe.de" PASSWORD="123" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <KUNDE PK_KUNDE="202" NACHNAME="Schillinger" VORNAME="David" EMAIL="david@hs-karlsruhe.de" PASSWORD="1234" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <KUNDE PK_KUNDE="203" NACHNAME="Reinhard" VORNAME="Marc" EMAIL="marc@hs-karlsruhe.de" PASSWORD="123" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <KUNDE PK_KUNDE="204" NACHNAME="Pfefferle" VORNAME="Patrick" EMAIL="patrick@hs-karlsruhe.de" PASSWORD="123" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <KUNDE PK_KUNDE="205" NACHNAME="Schmitt" VORNAME="Sebastian" EMAIL="sebastian@hs-karlsruhe.de" PASSWORD="asd123" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <KUNDE PK_KUNDE="206" NACHNAME="Mustermann" VORNAME="Max" EMAIL="max@musteremail.de" PASSWORD="123" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <KUNDE PK_KUNDE="207" NACHNAME="Maier" VORNAME="Anton" EMAIL="anton@web.de" PASSWORD="123" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <KUNDE PK_KUNDE="208" NACHNAME="Schmitt" VORNAME="Elsa" EMAIL="elsa@hs-karlsruhe.de" PASSWORD="123" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <KUNDE PK_KUNDE="209" NACHNAME="Müller" VORNAME="Tanja" EMAIL="tanjam@web.de" PASSWORD="123" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <KUNDE PK_KUNDE="210" NACHNAME="Kramer" VORNAME="Miriam" EMAIL="mirik@web.de" PASSWORD="123" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <ADRESSE PK_ADRESSE="100" PLZ="69168" ORT="Wiesloch" STRASSE="Hauptstrasse" HAUSNR="8" FK_KUNDE="201" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <ADRESSE PK_ADRESSE="101" PLZ="69126" ORT="Rohrbach" STRASSE="Gartenstrasse" HAUSNR="10" FK_KUNDE="202" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <ADRESSE PK_ADRESSE="102" PLZ="76133" ORT="Karlsruhe" STRASSE="Karlsstrasse" HAUSNR="34" FK_KUNDE="203" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <ADRESSE PK_ADRESSE="103" PLZ="79576" ORT="Weil am Rhein" STRASSE="Schweizerstrasse" HAUSNR="87" FK_KUNDE="204" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <ADRESSE PK_ADRESSE="104" PLZ="68723" ORT="Plankstadt" STRASSE="Heilbronnerallee" HAUSNR="1" FK_KUNDE="205" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <ADRESSE PK_ADRESSE="105" PLZ="76646" ORT="Bruchsal" STRASSE="Brobinenweg" HAUSNR="38" FK_KUNDE="206" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <ADRESSE PK_ADRESSE="106" PLZ="70567" ORT="Stuttgart" STRASSE="Ulmenweg" HAUSNR="104" FK_KUNDE="207" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <ADRESSE PK_ADRESSE="107" PLZ="81243" ORT="München" STRASSE="Säbenerstrasse" HAUSNR="1" FK_KUNDE="208" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <ADRESSE PK_ADRESSE="108" PLZ="44267" ORT="Dortmund" STRASSE="Stadionallee" HAUSNR="99" FK_KUNDE="209" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <ADRESSE PK_ADRESSE="109" PLZ="69151" ORT="Heidelberg" STRASSE="Hauptstrasse" HAUSNR="33" FK_KUNDE="210" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <ARTIKEL PK_ARTIKEL="101" KATEGORIE="Herren" BESCHREIBUNG="Hemd" PREIS="80.0" AUF_LAGER="54" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <ARTIKEL PK_ARTIKEL="102" KATEGORIE="Damen" BESCHREIBUNG="Bluse" PREIS="55.0" AUF_LAGER="24" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <ARTIKEL PK_ARTIKEL="103" KATEGORIE="Herren" BESCHREIBUNG="Hose" PREIS="80.0" AUF_LAGER="15" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <ARTIKEL PK_ARTIKEL="104" KATEGORIE="Kinder" BESCHREIBUNG="Schuhe" PREIS="20.0" AUF_LAGER="31" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <ARTIKEL PK_ARTIKEL="105" KATEGORIE="Kinder" BESCHREIBUNG="Pullover" PREIS="25.0" AUF_LAGER="16" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <ARTIKEL PK_ARTIKEL="106" KATEGORIE="Herren" BESCHREIBUNG="Guertel" PREIS="20.0" AUF_LAGER="5" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <ARTIKEL PK_ARTIKEL="107" KATEGORIE="Damen" BESCHREIBUNG="Hose" PREIS="70.0" AUF_LAGER="14" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <ARTIKEL PK_ARTIKEL="108" KATEGORIE="Damen" BESCHREIBUNG="Unterwaesche" PREIS="40.0" AUF_LAGER="20" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <ARTIKEL PK_ARTIKEL="109" KATEGORIE="Damen" BESCHREIBUNG="Badeanzug" PREIS="30.0" AUF_LAGER="34" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <ARTIKEL PK_ARTIKEL="110" KATEGORIE="Herren" BESCHREIBUNG="Socken" PREIS="10.0" AUF_LAGER="5" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <BESTELLUNG PK_BESTELLUNG="101" FK_KUNDE="201" IDX="0" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <BESTELLUNG PK_BESTELLUNG="102" FK_KUNDE="201" IDX="0" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <BESTELLUNG PK_BESTELLUNG="103" FK_KUNDE="203" IDX="0" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <BESTELLUNG PK_BESTELLUNG="104" FK_KUNDE="204" IDX="0" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <BESTELLUNG PK_BESTELLUNG="105" FK_KUNDE="205" IDX="0" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <BESTELLUNG PK_BESTELLUNG="106" FK_KUNDE="206" IDX="0" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <BESTELLUNG PK_BESTELLUNG="107" FK_KUNDE="207" IDX="0" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <BESTELLUNG PK_BESTELLUNG="108" FK_KUNDE="208" IDX="0" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <BESTELLUNG PK_BESTELLUNG="109" FK_KUNDE="209" IDX="0" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <BESTELLUNG PK_BESTELLUNG="110" FK_KUNDE="210" IDX="0" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <POSITION PK_POSITION="101" FK_BESTELLUNG="101" FK_ARTIKEL="101" ANZAHL="1" IDX="0" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <POSITION PK_POSITION="102" FK_BESTELLUNG="102" FK_ARTIKEL="102" ANZAHL="4" IDX="0" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <POSITION PK_POSITION="103" FK_BESTELLUNG="103" FK_ARTIKEL="103" ANZAHL="103" IDX="0" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <POSITION PK_POSITION="104" FK_BESTELLUNG="104" FK_ARTIKEL="104" ANZAHL="50" IDX="0" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <POSITION PK_POSITION="105" FK_BESTELLUNG="105" FK_ARTIKEL="105" ANZAHL="10" IDX="0" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <POSITION PK_POSITION="106" FK_BESTELLUNG="106" FK_ARTIKEL="106" ANZAHL="70" IDX="0" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <POSITION PK_POSITION="107" FK_BESTELLUNG="107" FK_ARTIKEL="107" ANZAHL="100" IDX="0" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <POSITION PK_POSITION="108" FK_BESTELLUNG="108" FK_ARTIKEL="108" ANZAHL="50" IDX="0" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <POSITION PK_POSITION="109" FK_BESTELLUNG="109" FK_ARTIKEL="109" ANZAHL="30" IDX="0" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
  <POSITION PK_POSITION="110" FK_BESTELLUNG="110" FK_ARTIKEL="110" ANZAHL="125" IDX="0" ERZEUGT="2012-10-10 00:00:00.0" AKTUALISIERT="2012-10-10 00:00:00.0"/>
</dataset>
